### ISSUE TITLE
Single file in `files` list is creating a folder

### ISSUE THREAD

**Issue by mattpardee** [gruntjs/grunt-contrib-compress#101]
I can't figure out how to get a single file to end up in the root directory of the zip file. When I run the code below, the directory structure from the expanded zip includes `manifest.json` as a _folder_ -- not as a single file.

![](http://content.screencast.com/users/matt.pardee/folders/Jing/media/51d2e436-2611-4adc-a4cb-7fe1617c1de5/00000196.png)

The code:

``` javascript
compress: {
      chromeapp: {
        files: [{
            src: 'build/chrome/manifest.json',
            dest: 'manifest.json'
        }
      }
      //...
}
```

Any ideas?

**Comment by paambaati** [comment]
Just in case anyone else is looking for this exact issue, here's how you configure your task.

```
compress: {
      chromeapp: {
        files: [{
            src: 'build/chrome/manifest.json'
        }
      }
      //...
}
```

The trick is to skip the `dest` parameter. This preserves the file path and name.
