### ISSUE TITLE
Default compression level of 1 should be 9

### ISSUE THREAD

**Issue by jwineinger** [gruntjs/grunt-contrib-compress#116]
Is there a good reason to use the lowest compression level by default instead of the highest?

**Comment by mgeisler** [comment]
Are you aware that the decompression speed changes much less than the compression speed? I took some random Python, JavaScript, C, and Java files and concatenated them into a big 71 MB file:

```
% ll random-source-code.txt 
-rw-r--r-- 1 mg mg 71M Jan 21 17:23 random-source-code.txt
```

I then compressed it with `gzip -1` and uncompressed it:
```
% time gzip -1 random-source-code.txt 
gzip -1 random-source-code.txt  1.33s user 0.04s system 99% cpu 1.372 total
% ll random-source-code.txt.gz 
-rw-r--r-- 1 mg mg 17M Jan 21 17:23 random-source-code.txt.gz
% time gunzip random-source-code.txt.gz 
gunzip random-source-code.txt.gz  0.60s user 0.09s system 99% cpu 0.695 total
```
I did this a couple of times, the timing was very stable (+/-0.01 sec).

With `gzip -9` the numbers look like this:
```
% time gzip -9 random-source-code.txt   
gzip -9 random-source-code.txt  8.74s user 0.03s system 99% cpu 8.778 total
% ll random-source-code.txt.gz 
-rw-r--r-- 1 mg mg 14M Jan 21 17:23 random-source-code.txt.gz
% time gunzip random-source-code.txt.gz
gunzip random-source-code.txt.gz  0.52s user 0.08s system 98% cpu 0.612 total
```

What we see here is that using `gzip -9` takes significantly longer, but produces a 18% smaller file in this example. Uncompressing the smaller file produced by `gzip -9` is a little faster than uncompressing the larger file made by `gzip -1`.

I tried again with just some JavaScript files and got these numbers for a 1.3 MB file:
```
% ll source.js  
-rw-r--r-- 1 mg mg 1.3M Jan 21 17:35 source.js
% time gzip -1 source.js  
gzip -1 source.js  0.04s user 0.00s system 96% cpu 0.037 total
% ll source.js.gz 
-rw-r--r-- 1 mg mg 399K Jan 21 17:35 source.js.gz
% time gunzip source.js.gz  
gunzip source.js.gz  0.02s user 0.00s system 89% cpu 0.022 total
% time gzip -9 source.js 
gzip -9 source.js  0.10s user 0.00s system 97% cpu 0.098 total
% ll source.js.gz         
-rw-r--r-- 1 mg mg 332K Jan 21 17:35 source.js.gz
% time gunzip source.js.gz
gunzip source.js.gz  0.01s user 0.01s system 95% cpu 0.021 total
```

We see again that the uncompress time is virtually unchanged, if not a little better.

**Comment by felicienfrancois** [comment]
@mgeisler gzip seems to have a decompression speed that does not vary with compression level but this is not the case with zip for example.

On top of that, if you really care about 18% of your archive size, you should first look at your code and assets, you'll be able to gain much much more by removing unused code and libraries and optimizing images. If so, you're in the very small part who care about.

Additionally, node is mostly used to develop and package web apps. The archive is uploaded to the server and unziped once, unlike the build and zipping step that could be done more often locally, in test/dev environment. So gaining 7s of zipping is much more important than gaining 18% size for most users.

**Comment by ctalkington** [comment]
again agree with @felicienfrancois here. you can always set the level via option if you feel differently

**Comment by mgeisler** [comment]
The scenario I was thinking of was generating a compressed (and minified) version of my JavaScript, a file that would be generated once and downloaded by many clients. That's why I was interested in spending a little more time upfront compressing the file so that the clients may save a bit of time when downloading it.

If that's not the scenario you have in mind, then your considerations may of course change :-) It's fine as it is now -- I've already set the config option :-)
