### ISSUE TITLE
Executable perms lost

### ISSUE THREAD

**Issue by pirog** [gruntjs/grunt-contrib-compress#120]
Archiving some things, like a OSX App bundle results in some files being stripped of their executable permisison. However, this issue seems to be resolved by upgrading to the latest `node-archiver` aka `"archiver": "~0.11.0"`.

Not sure the other consequences of this so will not submit a PR until wisdom in imparted from maintainer.

**Comment by paambaati** [comment]
I'm facing this problem when I use a `rename` with a `src:dest` pair; the executable permissions for the renamed file are stripped. Is this a related issue?

**Comment by calaverastech** [comment]
We have this problem with OS X. The compress task strips off all permissions and changes the owner of the files - now it's root. It works fine with Linux. The grunt-contrib-compress version is 0.13.0.
