### ISSUE TITLE
Move to archiver > 0.11 broke recursive compression

### ISSUE THREAD

**Issue by gavllew** [gruntjs/grunt-contrib-compress#141]
With the new v0.13 release recursive directory compression seems to be broken, producing the following error:

    Fatal error: Maximum call stack size exceeded

I reproduced the error with the following basic project:

*package.json*
```javascript
{
  "name": "test",
  "version": "0.1.0",
  "homepage": "",
  "author": {},
  "engines": {
    "node": ">= 0.10.26"
  },
  "devDependencies": {},
  "dependencies": {
    "grunt": "^0.4.5",
    "grunt-contrib-compress": "^0.13.0",
    "grunt-contrib-copy": "^0.7.0",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-contrib-nodeunit": "^0.4.1",
    "grunt-contrib-jshint": "^0.10.0"
  },
  "keywords": []
}
```

*Gruntfile.js*
```javascript
module.exports = function(grunt) {
  // Project configuration.
  grunt.initConfig({
    compress: {
      dist: {
        options: {
          archive: 'dist/test.zip',
          mode: 'zip'
        },
        files: [
          {
            src: [
              'node_modules/**'
            ]
          }
        ]
      }
    }
  });

  // These plugins provide necessary tasks.
  grunt.loadNpmTasks('grunt-contrib-nodeunit');
  grunt.loadNpmTasks('grunt-contrib-jshint');
  grunt.loadNpmTasks('grunt-contrib-watch');
  grunt.loadNpmTasks('grunt-contrib-compress');

  // Default task.
  grunt.registerTask('default', ['compress']);
};
```

Rolling back to archiver v0.11 fixes the issue.

**Comment by sindresorhus** [comment]
// @ctalkington

**Comment by ctalkington** [comment]
I'll do some testing on my end. you should be able to easily use a prev version of compress in the meantime since the project uses semver.

**Comment by ctalkington** [comment]
this seems to come from the handling of stat process best i can tell. will need to make some tests to recreate via archiver. interesting if the stats from task are passed through then it works fine (this is something allowed in newer versions to reduce fs lookups)

**Comment by ctalkington** [comment]
archiver v0.13.1 should address this issue.

**Comment by gavllew** [comment]
Thanks, that's fixed it for me.
