### ISSUE TITLE
Different results between zip and gzip modes

### ISSUE THREAD

**Issue by msieurtoph** [gruntjs/grunt-contrib-compress#142]
Hi,

Thx for your plugin, but I probably miss something about usage.
I am trying to get one archive containing all my built files.

Using this gives me the expected result : 

```javascript
        compress: {
            dist: {
                options: {
                    archive: './archive.zip',
                    mode: 'zip'
                },
                files: [{
                    expand: true,
                    cwd: 'dist/',
                    src: '**'
                }]
            }
        },
```

But, when I try to get an gzip archive, using the following options (the same than before except the `mode` and `archive`), the plugin does not create the archive and instead creates a compressed version of each files at the root level `./` and subdirs (overriding some existing source files of course, because new files are not renamed at all) :

```javascript
        compress: {
            dist: {
                options: {
                    archive: './archive.gzip',
                    mode: 'gzip'
                },
                files: [{
                    expand: true,
                    cwd: 'dist/',
                    src: '**'
                }]
            }
        },
```

I thought changing `mode` would only change the compression of the final archive ... it seems not.
What did I miss ?

Thx in advance ;)

**Comment by ctalkington** [comment]
gzip isn't an archive format. you need to use tar mode to compress into gzip
