### ISSUE TITLE
Not works with grunt-newer

### ISSUE THREAD

**Issue by ArtemFitiskin** [gruntjs/grunt-contrib-compress#144]
I'm trying to use it with [grunt-newer](https://github.com/tschaub/grunt-newer) like this:

```
grunt.registerTask('default', [
    'test',
    'build',
    'newer:compress' // this
]);
```

Is it available? Working fine without newer.

**Comment by sindresorhus** [comment]
> Working fine without newer.

Doesn't that tell you everything you need about where this should be opened.
