### ISSUE TITLE
dest: being ignored - saving zip in root path

### ISSUE THREAD

**Issue by badfeather** [gruntjs/grunt-contrib-compress#145]
Hi, I have the following:
```
    compress: {
      main: {
        options: {
          archive: 'example.zip'
        },
        files: [
          {src: ['dist/example/**'], dest: 'dist/', filter: 'isFile'}
        ]
      }
    }
```
The archive is being created, but is being saved in the root directory of my project, not in the `dist/` subdirectory. I've tried changing the `dest: ` to other things well, with same result. Any thoughts?

**Comment by ctalkington** [comment]
`dest` refers to the inside of zip structure. you would add dist/ to you `archive` option.

**Comment by badfeather** [comment]
Ah, ok. Thanks for the clarification.

**Comment by badfeather** [comment]
Out of curiosity, is it possible to not have a `dist` or other subdirectory in the unzipped archive? Ie. if you extract `example.zip`, it opens a directory called `example` with all the enclosed files?

**Comment by ctalkington** [comment]
you would use a combination of `cwd` and `expand:true`

from readme
```js
{expand: true, cwd: 'path/', src: ['**'], dest: 'internal_folder3/'}, // makes all src relative to cwd
```

**Comment by badfeather** [comment]
Ah, great. Thank you.

**Comment by askupasoftware** [comment]
I had a similar issue. `expand: true` solved it. @ctalkington thanks for clarifying this subject.

**Comment by bjmiller121** [comment]
I got caught by this as well. Would be great to get a bit more clarification in the documentation that the `archive` option can be a path, not necessarily just the filename of the resulting compressed archive. It would also be great to have some clarification int he docs on how `dest` works since it's not very intuitive at first.
