### ISSUE TITLE
Compiler error.

### ISSUE THREAD

**Issue by emalherbi** [gruntjs/grunt-contrib-compress#146]
Hey there!

I received the following error on the console.

```javascript
dist-crypto/class.pop3.php - PHP 5.0 compiler error: line 318, Multiple access type modifiers are not allowed [2]
```

So I open the php code to check. 

```php
  /**
   * Get the socket response back.
   * $size is the maximum number of bytes to retrieve
   * @access private
   * @param integer $size
   * @return string
   */
  private public function getResponse ($size = 128) {
    $pop3_response = fgets($this->pop_conn, $size);

    return $pop3_response;
  }
```
This class is the [phpmailer](https://github.com/PHPMailer/PHPMailer) project.

And I also open the file generated by compression and the file was there. What is the reason for this error ? 

Thank you.

**Comment by sindresorhus** [comment]
I think you might have opened this on the wrong repo.
