### ISSUE TITLE
Warning: unable to stat srcFile (common) Use --force to continue

### ISSUE THREAD

**Issue by srad** [gruntjs/grunt-contrib-compress#151]
Is something wrong with this config?:

```javascript
   compress: {
            dist: {
                options: {
                    archive: 'my.zip',
                    mode:    'zip'
                },
                cwd:     '../build',
                src:     ['**'],
                dest:    '../'
            }
        },
```

Because I get: ```Warning: unable to stat srcFile (common) Use --force to continue.```

**Comment by benhutchins** [comment]
I was having a similar issue, it looks like you need to add `expand: true` to your configuration based on [grunt docs](http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically).

**Comment by Herudea** [comment]
I was experiencing this as well, but as @benhutchins said, `expand: true` did the trick.

**Comment by kenny-evitt** [comment]
Adding `expand: true` also resolved the warning for me too.
