### ISSUE TITLE
Reduce logging

### ISSUE THREAD

**Issue by tandrewnichols** [gruntjs/grunt-contrib-compress#154]
I realize there's another issue about the amount of logging, but it's dealing with a different line. Surely, there should be an option to turn off this line: https://github.com/gruntjs/grunt-contrib-compress/blob/c7c353ecaa5b827d82e42772f8ced948a7819621/tasks/lib/compress.js#L76

I'm tired of seeing this in our builds: 

<img width="755" alt="screen shot 2015-07-14 at 3 43 23 pm" src="https://cloud.githubusercontent.com/assets/2755760/8683161/2101b744-2a3f-11e5-85d0-bbd26c980a10.png">

Incidentally, that goes on for more than twice as much as is shown there. I just want a "quiet" option to make travis builds actually consumable.

**Comment by vladikoff** [comment]
Yeah the logging should be converted to use `verbose`.
https://github.com/gruntjs/grunt-contrib-clean/blob/master/tasks/clean.js#L38
