### ISSUE TITLE
Files with more than one period are ignored

### ISSUE THREAD

**Issue by slooker** [gruntjs/grunt-contrib-compress#157]
Originally my gruntfile.js had this section:

    compress: {
      main: {
        options: {
          mode: 'gzip',
        },
        files: [
          { expand: true, src: ['build/<%= pkg.version %>/js/*.js'], ext: '.js.gz' },
          { expand: true, src: ['build/<%= pkg.version %>/js/libs/*.*.js'], ext: '.js.gz' },
        ]
      }
    },

But then I noticed that certain files weren't getting gzipped.  In this case, jquery.emojipicker.a.js.  So I changed my compress files section to add this:

     { expand: true, src: ['build/<%= pkg.version %>/js/jquery.emojipicker.a.js'], ext: '.js.gz' },

But it's still being ignored.

**Comment by ctalkington** [comment]
`extDot: last`

see http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically

**Comment by slooker** [comment]
Works great, thank you. Can the docs be updated to reflect that?

**Comment by schmoove** [comment]
+1 please update README to include this
