### ISSUE TITLE
New option to keep symlinks

### ISSUE THREAD

**Issue by romaincointepas** [gruntjs/grunt-contrib-compress#167]
Right now it replaces all symlinks with the linked file.

(I'm developing an app with https://github.com/atom/electron and the resulting .app on Mac includes some symlinks).

**Comment by elronalds** [comment]
Is there a patch or workaround available for this?  Also trying to compress an electron.js app and the symlinks are not preserved making the app 3x larger.

**Comment by ctalkington** [comment]
is this zip? archiver would need to support symlinks in zips for such to be possible.

**Comment by romaincointepas** [comment]
I'm Mac I'm using `zip -y`, works like a charm.

**Comment by elronalds** [comment]
Yes, I had to revert to using the command line for this, also using the `zip -y` flag.  Would be nice to have this fixed so we can go back to using grunt.

**Comment by romaincointepas** [comment]
+1.

(BTW, you can use https://github.com/sindresorhus/grunt-shell for this).

**Comment by elronalds** [comment]
Looks like there is a bug already open for this at https://github.com/archiverjs/node-archiver/issues/158
