### ISSUE TITLE
Output not verbose enough on 0.14

### ISSUE THREAD

**Issue by larpo** [gruntjs/grunt-contrib-compress#168]
On 0.13 the grunt task would print the name of the archive file that was created. Being able to see the name of the created files was very useful because the next thing that usually happened after creating the bundle was to scp it to various places.
```
Running "compress:dist" (compress) task
Created packagename-958f9d5-20151029-0814.tar.gz (736.8 kB)
```
Now, after updating to 0.14 the output less useful:
```
Running "compress:dist" (compress) task
>> Compressed 24 files.
```

I'm using following config:
```
 "compress": {
            "dist": {
                "options": {
                    archive: "packagename-<%= meta.revision %>-" + dateString + ".tar.gz",
                    mode: "tgz",
                    pretty: true
                },
                files: [
                    {expand: true, cwd: 'dist', src: ['**'], dest: 'packagename'}
                ]
            }
```

Is there a way to make the output more verbose and print at least the name of the created archive file?

**Comment by jrcryer** [comment]
Hi @larpo - the feature is still there but you need to run the task with verbose flag set.  See dd92183c82a5b62b602ab004f1c69d23a2ffcccf for the change. Hope this helps!
