### ISSUE TITLE
non-empty string error at 0.14.0

### ISSUE THREAD

**Issue by stdavis** [gruntjs/grunt-contrib-compress#170]
After upgrading to 0.14.0 I get the following error:
```
Files: dist/xstyle/util/getComputedStyle.js.map -> xstyle/util/getComputedStyle.js.map
Files: dist/xstyle/xstyle.js -> xstyle/xstyle.js
Options: archive="deploy/deploy.zip", mode=null, level=1
>> Error: append: entry name must be a non-empty string value
Warning: Archiving failed. Use --force to continue.
```

Downgrading to 0.13.0 fixes the issue.

**Comment by jrcryer** [comment]
Hi @stdavis - do you have an example Gruntfile to share? Ta

**Comment by stdavis** [comment]
https://github.com/agrc/ugs-chemistry/blob/master/Gruntfile.js

**Comment by jrcryer** [comment]
Thanks - I'll take a look now

**Comment by stdavis** [comment]
Thanks for taking a look!

**Comment by jrcryer** [comment]
No problem - looks like a issue introduced in [d763660](https://github.com/gruntjs/grunt-contrib-compress/commit/#diff-53e4a321861f65ba4ed86a8eecbf422eL125).  I'll see if I can re-create with a broken test and get a PR raised.

**Comment by steveoh** [comment]
is this going to get pushed out in a new version soon?
