### ISSUE TITLE
How can I add a dot file into the archive file?

### ISSUE THREAD

**Issue by xjmalm** [gruntjs/grunt-contrib-compress#173]
From the release history, it says that "Prevent zipping dot files“ since v0.12.0. But now I'd like to add a dot file (for e.g., file .abc) into the archive file, how can I handle this?

Thanks in advance.

**Comment by ctalkington** [comment]
this should only impact single dot as file name if i recall correctly. using `glob` you may need to set the following glob option to `true`

dot: Include .dot files in normal matches and globstar matches. Note that an explicit dot in a portion of the pattern will always match dot files.

**Comment by ctalkington** [comment]
related commit https://github.com/gruntjs/grunt-contrib-compress/commit/19a95735874d46c3b18685e22e4d8d68e55eac78 

it only checks for single dot if you have `.abc` this should work fine.

**Comment by xjmalm** [comment]
Thanks ctalkington for the help.
You are right it is the consumer configuration issue, I used the source files configuration like following, it excludes the files like .abc:
  src: ['xx/**/*']
and then I change to following, it works as I expected now:
 src: ['xx/**/*', 'xx/**/.*']
