### ISSUE TITLE
Task fails due to Warning: grunt.util._.include is not a function

### ISSUE THREAD

**Issue by petetnt** [gruntjs/grunt-contrib-compress#177]
The following line throws with `Grunt-1.0.0-rc1` with `grunt-contrib-compress-1.1.1.`

https://github.com/gruntjs/grunt-contrib-compress/blob/3ea4386afc851056e2c4559b58b6a11c00b9bd34/tasks/compress.js#L27

```
    if (grunt.util._.include(['zip', 'tar', 'tgz', 'gzip', 'deflate', 'deflateRaw'], compress.options.mode) === false) {
      grunt.fail.warn('Mode ' + String(compress.options.mode).cyan + ' not supported.');
    }
```

This is due to [Grunt updating to `lodash 4.3.0`](https://github.com/gruntjs/grunt/blob/master/CHANGELOG#L26) which removed [the alias `_.include` in favor of `_.includes` in 4.0.0.](https://github.com/lodash/lodash/wiki/Changelog#v400).

([grunt.util._ is deprecated and should most likely not be used anyway](http://gruntjs.com/api/grunt.util#grunt.util._))

My task:
``` js
compress: {
  foo: {
    options: {
      archive: "foo/bar.zip"   
    },
    files: [{
      expand: true,
      flatten: true,
      cwd: 'foo/',
      src: ['**', '!*.zip'],
      filter: 'isFile'
    }]
  }
}
```

**Comment by vladikoff** [comment]
cc @shama

**Comment by shama** [comment]
Thanks for the great issue report @petetnt!

**Comment by petetnt** [comment]
Thanks for the fix :+1:
