### ISSUE TITLE
If encoding is specified then the first argument must be a string. nodejs v6.0.0

### ISSUE THREAD

**Issue by StickyCube** [gruntjs/grunt-contrib-compress#180]
When running the compress task on nodejs v6.0.0, I get the following error:

> If encoding is specified then the first argument must be a string

The following minimal Gruntfile, which works in nodejs v5.x, reproduces this:

Gruntfile.js
```javascript
'use strict';
module.exports = grunt => {
  grunt.initConfig({
    compress: {
      build: {
        options: {
          mode: 'tar',
          archive: 'compressed.tar'
        },
        files: [{
          cwd: 'assets',
          src: '**',
          expand: true
        }]
      }
    }
  });

  grunt.loadNpmTasks('grunt-contrib-compress');
};
```

The file `compressed.tar` is generated but the task reports failure

I cant see in the source where this might be originating, maybe it's an issue in a dependency?

Cheers

**Comment by stevermeister** [comment]
👍

**Comment by besuhoff** [comment]
+1

**Comment by EdwardDiehl** [comment]
+1

**Comment by imathews** [comment]
+1

**Comment by cesarfd** [comment]
+1

**Comment by mintrupt** [comment]
+1

**Comment by splintor** [comment]
+1

**Comment by splintor** [comment]
Seems like upgrading to archiver version 1.0.0 will fix this.

**Comment by imathews** [comment]
Can we get a new release to incorporate this fix?

**Comment by tejasmulay** [comment]
I am facing same problem as described above:
"Running "artifactory:client:publish" (artifactory) task
Fatal error: If encoding is specified then the first argument must be a string".

I tried to install archiver and contrib-compress on the host but I still get same error. 
I am running below commands:
npm install archiver@1.0.0
npm install grunt-contrib-compress@1.3.0

Is there anything I am missing? 
I first installed as root user, did not work, then installed using -g option, did not work, then installed using build user, did not work. Then I also added above two lines into build script which looks like this:
**********************
npm install archiver@1.0.0
npm install grunt-contrib-compress@1.3.0

npm install bower
./node_modules/bower/bin/bower cache clean
./node_modules/bower/bin/bower install --force
./node_modules/bower/bin/bower prune
npm install

./node_modules/protractor/bin/webdriver-manager update

grunt ddescribe-iit --no-color
grunt test build --no-color
**********************
But still build is failing with same message. Can anybody provide quick help please?
-Tejas.

**Comment by mmamane** [comment]
Also seeing this problem with the following versions:

> node-v6.9.4 (binary)
> grunt-contrib-compress@1.4.1

However, I only encounter this error when executed within an RPM spec using the local compress version:

`%build
cd %{project}
npm install
bower install
grunt build`

Using a global install of compress works fine.  Is this expected?

**Comment by shareef926** [comment]
ii is working for me with the node version 0.10.21

**Comment by shareef926** [comment]
It is working for by changing the node version to v0.10.21
