### ISSUE TITLE
Pleas help: Error: Cannot find module 'glob'

### ISSUE THREAD

**Issue by danniejpt** [gruntjs/grunt-contrib-compress#181]
I got this message error when try to run `grunt compress`

```
Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
```

Here are my `Gruntfile.js`

```
module.exports = function (grunt) {
  // Define a zip task
  grunt.initConfig({
    compress: {
      main: {
        options: {
          archive: 'package/test.zip'
        },
        files: [
          {src: ['wp-content/themes/bs-smarty/**']}, // includes files in path
        ]
      }
    }
  });

  grunt.loadNpmTasks('grunt-contrib-compress');
};
```

Thank you

**Comment by sharikovvladislav** [comment]
Are you sure you installed all dependencies correctly?

Try this:

1) remove `node_modules` folder in your project (something like `rm -rf node_modules` in your project directory)
2) clean cache with `npm cache clean` command
3) install dependencies again with `npm i`

**Comment by XhmikosR** [comment]
@sharikovvladislav suggestion is what you should do if this still happens for you.
