### ISSUE TITLE
iltorb inclusion fails builds on environments without GCC/G++ compilers

### ISSUE THREAD

**Issue by dragonjet** [gruntjs/grunt-contrib-compress#190]
The recent inclusion of the dependency `iltorb` fails our travis builds.

We have included this as dependency
```
"grunt-contrib-compress": "^1.1.1",
```

Our builds suddenly went from [successful](https://travis-ci.org/KC3Kai/KC3Kai/builds/193080246) to [failed](https://travis-ci.org/KC3Kai/KC3Kai/builds/193192438).

This is because of the sudden inclusion of
```
> iltorb@1.0.13 install /home/travis/build/KC3Kai/KC3Kai/node_modules/iltorb
> node-gyp rebuild
```
in the build (Node 6) without the GCC/G++ Addons/Compilers. This made the `node-gyp rebuild` fail.

If anyone else is reading this for the same situation, and unable to figure out a fix / or just want to fix it quick, just stick your dependency to a lower version. [In our case, just removed `^`](https://github.com/KC3Kai/KC3Kai/pull/1746/files). Making it look like this:
```
"grunt-contrib-compress": "1.1.1",
```

This will pull a specific version of `grunt-contrib-compress` that doesnt have `iltorb`. If you know of a higher version without `iltorb` please let me know as well. The grunt-contrib-compress developers should know which version.

My general recommendation, is just bump the version to 2.x.x since there's really a backward incompatibility. Though you guys are still free to number it whichever, but I'd just wanna let you know in case you want to announce it / give notice to others.

Edit; to those who want the true fix while getting the latest version of `grunt-contrib-compress`, follow [travis guide for including GCC/G++ compilers](https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements)

**Comment by davewhiteley** [comment]
Same issue. Pegged to `grunt-contrib-compress@1.3.0` for now

**Comment by vladikoff** [comment]
@XhmikosR should we pull the brotli compressor or should we make the dep optional?

**Comment by tivnet** [comment]
Fails also under Cygwin. Even after windows-build-tools installed.

**Comment by XhmikosR** [comment]
@vladikoff: this is unfortunate :/ 

I expected that it would use the pre-built binaries when the system lacks of the compiler... apparently it doesn't and CI environments have the needed compiler.

How do you mean make it optional?

**Comment by XhmikosR** [comment]
Or you just mean https://docs.npmjs.com/files/package.json#optionaldependencies?

**Comment by XhmikosR** [comment]
Can someone try the iltorb-optional branch?

"grunt-contrib-compress": "https://github.com/gruntjs/grunt-contrib-compress.git#iltorb-optional"`?

**Comment by tivnet** [comment]
Haven't tried yet, but the patch looks OK. Awaiting for the release.

Thank you!

**Comment by tivnet** [comment]
BTW, under Windows / Cygwin, they do not want a C++. They want to install a "windows tools" package. However, even after it's installed successfully, compilation fails.

(I am a multi-OS guy. Need to have everything working on all of them :) )

**Comment by XhmikosR** [comment]
Well, I'm on Windows with VS2015 installed and works fine. The same it did for our Windows CI (AppVeyor).

**Comment by tivnet** [comment]
Windows / **Cygwin**
