### ISSUE TITLE
v1.4.0 breaks grunt-browser-sync's auto reload functionality

### ISSUE THREAD

**Issue by kevinmpowell** [gruntjs/grunt-contrib-compress#193]
I have no idea why, but I made a reduced test case to confirm:

with this `package.json`, Browser Sync's auto reload functionality works
````
  "devDependencies": {
    "grunt": "^1.0.1",
    "grunt-browser-sync": "^2.2.0",
    "grunt-contrib-compress": "1.3.0",
    "load-grunt-tasks": "^3.5.2"
  }
````

with this `package.json`, Browser Sync's auto reload functionality does not work
````
  "devDependencies": {
    "grunt": "^1.0.1",
    "grunt-browser-sync": "^2.2.0",
    "grunt-contrib-compress": "^1.4.1",
    "load-grunt-tasks": "^3.5.2"
  }
````

We've locked our projects to grunt-contrib-compress 1.3.0 for the time being.

**Comment by XhmikosR** [comment]
Does this still happen? It's weird that it's affecting other packages; it shouldn't happen.

Can you try purging your local node_modules and see if it still happens?

**Comment by kevinmpowell** [comment]
@XhmikosR I'm no longer using this plugin.
