### ISSUE TITLE
optional brotli dependency breaks windows installs

### ISSUE THREAD

**Issue by Pomax** [gruntjs/grunt-contrib-compress#195]
running `npm install` on windows causes the optional brotli dependency to get pull down and compiled, which is a pretty guaranteed break on any machine that doesn't even use brotli compression and has no need to otherwise run any node-gyp compiles. As this is but one in a million utility extensions for grunt, running with `--no-optional` is not really an option, as there are plenty of other utils for which the optional dependencies *do* work.

Can this lib tap into prebuilt `iltorb` libs, or be split up such that `grunt-contrib-compress` is compile-less compressors, with an optional additional install of `grunt-contrib-compress-brotli` so that this can be installed, or left off, separately, thus not causing cross-platform compatibility issues?

**Comment by MayhemYDG** [comment]
iltorb now offers pre-built binaries.

**Comment by Pomax** [comment]
@MayhemYDG that's great to hear! The README.md still talks about needing to manually compile, is it missing a leading docs section to explain that compiling is only necessary when there is no precompiled binary available for the particular OS the user is on?

**Comment by MayhemYDG** [comment]
The readme has been updated to reflect the recent changes.

**Comment by Pomax** [comment]
Nice! can you do a patch release to npm too (1.2.1) so that the new README is picked up there, too? This si super cool, thanks so much for the hard work!

**Comment by MayhemYDG** [comment]
I'm working on updating brotli, so a new release will happen soonish.
