### ISSUE TITLE
Release 1.4.3 breaking builds

### ISSUE THREAD

**Issue by BJJLangedijk** [gruntjs/grunt-contrib-compress#198]
Hi,

We are using this package to compress files into ZIPs, seems straight forward. However, we are using Node 0.10 for the build server and that has starting to break lately.

We are using the package:
"grunt-contrib-compress": "^1.2.0",

This however, since it uses the caret, will take the 1.*.* version, which will take the latest (1.4.3) tag. The 1.4.3 tag requires a package ("pretty-bytes": "^4.0.2",) which requires Node >=4 and uses some functionality that is unavailable on Node 0.10 and thus fails on our Node 0.10 build server.

The upgrade of the dependency in my eyes doesn't seem like a minor release since it has quite an effect on the requirements of this package.

We have solved the problem ourselves by sticking to:
"grunt-contrib-compress": "1.4.2",

This is not an issue, more like FYI and discuss point about how versions are released.

Regards,

**Comment by XhmikosR** [comment]
Well, we only test node.js v4 and newer that's why the issue slipped. I will release a patch version with the update reverted and drop < 4 support later.

**Comment by XhmikosR** [comment]
Actually, scratch that. Since the Brotli support patch, versions < 4 have issues. So I'm gonna change the required version in package.json to that instead.
