### ISSUE TITLE
Update iltorb to fix tar vulnerability and compatibility with Node 12

### ISSUE THREAD

**Issue by klimashkin** [gruntjs/grunt-contrib-compress#214]
Whenever you have time, the latest [iltorb 2.4.3](https://github.com/MayhemYDG/iltorb/blob/master/CHANGELOG.md#243---2019-04-24) fixes `tar` version  dependency and brings Node 12 support.

**Comment by fwextensions** [comment]
FWIW, I've forked this and updated the `iltorb` package here: https://github.com/fwextensions/grunt-contrib-compress/tree/fwextensions-update-iltorb

That can be included in `package.json` like `"grunt-contrib-compress": "fwextensions/grunt-contrib-compress#fwextensions-update-iltorb"`.  Not a long term solution, but gets rid of the vulnerability warnings for now.

**Comment by aarranz** [comment]
@fwextensions, what about creating a pull request? 😉😄
